#!/bin/sh
#
# ~/.xprofile

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && -merge ~/.Xresources

sh ~/.fehbg &

# exec gnome-session
# exec startkde
# exec startxfce4
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr
xmonad
# ...or the Window Manager of your choice
